"""System prompts for The Analyst agents."""

from src.prompts.agents import (
    ARABIC_NLP_PROMPT,
    INSIGHTS_PROMPT,
    MODELING_PROMPT,
    REPORT_PROMPT,
    RETRIEVAL_PROMPT,
    STATISTICAL_PROMPT,
    TRANSFORM_PROMPT,
    VISUALIZATION_PROMPT,
)
from src.prompts.orchestrator import ORCHESTRATOR_PROMPT

__all__ = [
    "ORCHESTRATOR_PROMPT",
    "RETRIEVAL_PROMPT",
    "TRANSFORM_PROMPT",
    "STATISTICAL_PROMPT",
    "ARABIC_NLP_PROMPT",
    "MODELING_PROMPT",
    "INSIGHTS_PROMPT",
    "VISUALIZATION_PROMPT",
    "REPORT_PROMPT",
]
